### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by anishmenon** [amitu/dcavenue#1]
when accessing url 

dcavenue-start

'D' object has no attribute 'mounts'

**Comment by amitu** [comment]
What version of importd are you using?

**Comment by anishmenon** [comment]
Sorry Amit . it was because of my configuration mistake :P .. Anyways Good job .

**Comment by amitu** [comment]
Cool. Do let me know if you end up using it, or find any issues. I built it for a very specific use case.
